language: go
sudo: false
install: true

matrix:
  include:
    - os: linux
      go: "1.13.x"
      sudo: true

    - os: osx
      go: "1.13.x"

    - os: linux-ppc64le
      go: "1.13.x"
      sudo: true

before_install:
  - env GO111MODULE=off go get -u golang.org/x/lint/golint

before_script:
  - mkdir $HOME/.kube
  - curl https://raw.githubusercontent.com/projectcalico/cni-plugin/master/kubeconfig.sample > $HOME/.kube/config

script:
  - env GO111MODULE=on GOFLAGS=-mod=vendor make ci
